name: FPKGi Duplication Check

on:
  workflow_dispatch:
  push:
    paths:
      - "ps4/**/*.json"
      - "ps5/**/*.json"
      - "changes/*.json"
      - "tools/duplicate_check.py"
      - ".github/workflows/duplicate_check.yml"

concurrency:
  group: fpkgi-catalog-duplicate-check
  cancel-in-progress: true

jobs:
  duplicate-check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.12"
      - name: Run Duplication Check
        run: |
          python tools/duplicate_check.py